CREATE EXTERNAL TABLE AREA     (
      N_NATIONKEY INTEGER,
      N_NAME CHAR(25),
      N_REGIONKEY INTEGER,
      N_COMMENT VARCHAR(152)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';

CREATE EXTERNAL TABLE CLIENT     (
      C_CUSTKEY INTEGER,
      C_NAME VARCHAR(25),
      C_ADDRESS VARCHAR(40),
      C_NATIONKEY INTEGER,
      C_PHONE CHAR(15),
      C_ACCTBAL DECIMAL(15,2),
      C_MKTSEGMENT CHAR(10),
      C_COMMENT VARCHAR(117)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';


CREATE EXTERNAL TABLE CONTRACT     (
      O_ORDERKEY INTEGER,
      O_CUSTKEY INTEGER,
      O_ORDERSTATUS CHAR(1),
      O_TOTALPRICE DECIMAL(15,2),
      O_ORDERDATE DATE FORMAT 'YYYY-MM-DD',
      O_ORDERPRIORITY VARCHAR(15),
      O_CLERK VARCHAR(15),
      O_SHIPPRIORITY INTEGER,
      O_COMMENT VARCHAR(79)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';



CREATE EXTERNAL TABLE EMPLOYEE     (
      EmpNo VARCHAR(15),
      Name VARCHAR(18),
      Address VARCHAR(40),
      Phone CHAR(15),
      DeptNo SMALLINT,
      Salary DECIMAL(8,2),
      YrsExp BYTEINT,
      DOB DATE FORMAT 'YYYY-MM-DD',
      MedStat CHAR(1),
      EdLev BYTEINT,
      Note VARCHAR(79)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';

CREATE EXTERNAL TABLE ITEM     (
      L_ORDERKEY INTEGER,
      L_PARTKEY INTEGER,
      L_SUPPKEY INTEGER,
      L_LINENUMBER INTEGER,
      L_QUANTITY DECIMAL(15,2),
      L_EXTENDEDPRICE DECIMAL(15,2),
      L_DISCOUNT DECIMAL(15,2),
      L_TAX DECIMAL(15,2),
      L_RETURNFLAG CHAR(1),
      L_LINESTATUS CHAR(1),
      L_SHIPDATE DATE FORMAT 'YYYY-MM-DD',
      L_COMMITDATE DATE FORMAT 'YYYY-MM-DD',
      L_RECEIPTDATE DATE FORMAT 'YYYY-MM-DD',
      L_SHIPINSTRUCT CHAR(25),
      L_SHIPMODE CHAR(10),
      L_COMMENT VARCHAR(44)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';



CREATE EXTERNAL TABLE ITEMPPI     (
      L_ORDERKEY INTEGER,
      L_PARTKEY INTEGER,
      L_SUPPKEY INTEGER,
      L_LINENUMBER INTEGER,
      L_QUANTITY DECIMAL(15,2),
      L_EXTENDEDPRICE DECIMAL(15,2),
      L_DISCOUNT DECIMAL(15,2),
      L_TAX DECIMAL(15,2),
      L_RETURNFLAG CHAR(1),
      L_LINESTATUS CHAR(1),
      L_SHIPDATE DATE FORMAT 'YYYY-MM-DD',
      L_COMMITDATE DATE FORMAT 'YYYY-MM-DD',
      L_RECEIPTDATE DATE FORMAT 'YYYY-MM-DD',
      L_SHIPINSTRUCT CHAR(25),
      L_SHIPMODE CHAR(10),
      L_COMMENT VARCHAR(44)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';




CREATE EXTERNAL TABLE PRODUCT     (
      P_PARTKEY INTEGER,
      P_NAME VARCHAR(55),
      P_MFGR CHAR(25),
      P_BRAND CHAR(10),
      P_TYPE VARCHAR(25),
      P_SIZE INTEGER,
      P_CONTAINER CHAR(10),
      P_RETAILPRICE DECIMAL(15,2),
      P_COMMENT VARCHAR(23)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';





CREATE EXTERNAL TABLE PROVIDER     (
      S_SUPPKEY INTEGER,
      S_NAME CHAR(25),
      S_ADDRESS VARCHAR(40),
      S_NATIONKEY INTEGER,
      S_PHONE CHAR(15),
      S_ACCTBAL DECIMAL(15,2),
      S_COMMENT VARCHAR(101)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';


CREATE EXTERNAL TABLE REGION     (
      R_REGIONKEY INTEGER,
      R_NAME CHAR(25),
      R_COMMENT VARCHAR(152)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|';
